name: Publish
on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  APP_NAME: danxi_backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest

      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@master
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Aliyun ACR
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ env.APP_NAME }}:latest
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }}

